language: node_js

node_js:
  - 10

sudo: true

addons:
  chrome: stable

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run lint ngx-resolver
  - npm run test ngx-resolver -- --watch false --browsers ChromeHeadless
